/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Automatas.AFD;
import Automatas.AFDTransicion;
import Ficheros.FicherosAutomatas;
import amcp2.GrafoAutomata;
import com.mxgraph.swing.mxGraphComponent;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class menu extends javax.swing.JFrame {

    private AFD automataAFD = new AFD();

    private HashSet<String> contenerdorEstados = new HashSet();
    private HashSet<String> contenedorSimbolos = new HashSet();
    GrafoAutomata grafico = new GrafoAutomata();

    private int iCadena = 0;
    private String estadoActual = "";

    public menu() {
        initComponents();
        setLocationRelativeTo(null);
        jRadioButtonAFD.setSelected(true);
        etiquetaEstadosFinales.setVisible(false);
        desplegableEstadosFinales.setVisible(false);

        jButtonPasoPaso.setEnabled(false);
        jButtonCompleto.setEnabled(false);

        jTextAreatoStringAutomata.setEditable(false);

        desplegableEstadoInicial.removeAllItems();
        desplegableEstadoFinal.removeAllItems();

        desplegableEstadoOrigen.removeAllItems();
        desplegableEstadoDestino.removeAllItems();
    }

    public void pintarLienzo() {
        jTextAreatoStringAutomata.setText(automataAFD.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEstadoAgregar = new javax.swing.JTextField();
        jButtonAgregarEstado = new javax.swing.JButton();
        etiquetaEstadoInicial = new javax.swing.JLabel();
        desplegableEstadoInicial = new javax.swing.JComboBox<>();
        etiquetaEstadoFinal = new javax.swing.JLabel();
        desplegableEstadoFinal = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        desplegableEstadoOrigen = new javax.swing.JComboBox<>();
        jTextFieldSimboloT = new javax.swing.JTextField();
        desplegableEstadoDestino = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jRadioButtonAFD = new javax.swing.JRadioButton();
        etiquetaEstadosFinales = new javax.swing.JLabel();
        jRadioButtonAFND = new javax.swing.JRadioButton();
        desplegableEstadosFinales = new javax.swing.JButton();
        jButtonPasoPaso = new javax.swing.JButton();
        jButtonCompleto = new javax.swing.JButton();
        jTextFieldCadena = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreatoStringAutomata = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Cargar Automata Fichero");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("CONF AUTOMATA");

        jLabel2.setText("Estados");

        jTextFieldEstadoAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstadoAgregarActionPerformed(evt);
            }
        });

        jButtonAgregarEstado.setText("Agregar estado");
        jButtonAgregarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarEstadoActionPerformed(evt);
            }
        });

        etiquetaEstadoInicial.setText("Estado Inicial");

        desplegableEstadoInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        etiquetaEstadoFinal.setText("Estado Final");

        desplegableEstadoFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("TRANSICIONES");

        desplegableEstadoOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        desplegableEstadoDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Estado Origen");

        jLabel7.setText("Estado Destino");

        jLabel8.setText("Simbolo");

        jButton3.setText("Agregar Transicion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonAFD);
        jRadioButtonAFD.setText("AFD");
        jRadioButtonAFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAFDActionPerformed(evt);
            }
        });

        etiquetaEstadosFinales.setText("Estados Finales");

        buttonGroup1.add(jRadioButtonAFND);
        jRadioButtonAFND.setText("AFND");
        jRadioButtonAFND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAFNDActionPerformed(evt);
            }
        });

        desplegableEstadosFinales.setText("Seleccionar");

        jButtonPasoPaso.setText("Paso a Paso");
        jButtonPasoPaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPasoPasoActionPerformed(evt);
            }
        });

        jButtonCompleto.setText("Completo");
        jButtonCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompletoActionPerformed(evt);
            }
        });

        jLabel3.setText("Cadena a Reconocer");

        jTextAreatoStringAutomata.setColumns(20);
        jTextAreatoStringAutomata.setRows(5);
        jScrollPane3.setViewportView(jTextAreatoStringAutomata);

        jButton1.setText("Agregar I/D");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Dibujar Automata");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1)
                                .addGap(41, 41, 41)
                                .addComponent(jRadioButtonAFD)
                                .addGap(31, 31, 31)
                                .addComponent(jRadioButtonAFND))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jTextFieldEstadoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(jButtonAgregarEstado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(etiquetaEstadoInicial)
                                        .addGap(18, 18, 18)
                                        .addComponent(desplegableEstadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(etiquetaEstadoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(desplegableEstadoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(etiquetaEstadosFinales)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(desplegableEstadosFinales))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(290, 290, 290)
                                        .addComponent(jButton3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(desplegableEstadoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(jLabel8))
                                                    .addComponent(jTextFieldSimboloT, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(36, 36, 36)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(desplegableEstadoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jButton1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jButtonCompleto)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonPasoPaso))
                                .addComponent(jTextFieldCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(183, 183, 183))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(jButton4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonAFD)
                                    .addComponent(jRadioButtonAFND))
                                .addGap(28, 28, 28)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEstadoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAgregarEstado)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonPasoPaso)
                                    .addComponent(jButtonCompleto))))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(etiquetaEstadoFinal)
                                    .addComponent(desplegableEstadoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiquetaEstadoInicial)
                                    .addComponent(desplegableEstadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiquetaEstadosFinales)
                                    .addComponent(desplegableEstadosFinales))
                                .addGap(30, 30, 30)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldSimboloT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(desplegableEstadoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(desplegableEstadoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        iCadena = 0;
        EmergenteCargado Em = new EmergenteCargado(this);
        String nombreArchivo = Em.getNombreElegido();
        mxGraphComponent dibujo;

        if (nombreArchivo != null) {

            nombreArchivo = "datos/" + nombreArchivo;

            try {
                automataAFD = FicherosAutomatas.lecturaAFD(nombreArchivo);
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }

            contenerdorEstados.addAll(automataAFD.getEstados());
            dibujo = grafico.pintarAFD(automataAFD, contenerdorEstados);
            if (grafico.isDibujoCompleto()) {
                jButtonPasoPaso.setEnabled(true);
                jButtonCompleto.setEnabled(true);
            }

            jScrollPane2.add(dibujo);
            jScrollPane2.getViewport().add(dibujo);
            jScrollPane2.revalidate();
            jScrollPane2.repaint();
            
            
            HashSet<String> estadosCargados = automataAFD.getEstados();
            for(String e : estadosCargados){
                if(!e.equals("-")){
                    
                    desplegableEstadoInicial.addItem(e);
                    desplegableEstadoFinal.addItem(e);
                    desplegableEstadoOrigen.addItem(e);
                    desplegableEstadoDestino.addItem(e);
                }
            }
            
        }

        pintarLienzo();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldEstadoAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstadoAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstadoAgregarActionPerformed

    private void jRadioButtonAFNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAFNDActionPerformed

        etiquetaEstadosFinales.setVisible(true);
        desplegableEstadosFinales.setVisible(true);

        etiquetaEstadoFinal.setVisible(false);
        desplegableEstadoFinal.setVisible(false);


    }//GEN-LAST:event_jRadioButtonAFNDActionPerformed

    private void jRadioButtonAFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAFDActionPerformed
        etiquetaEstadoFinal.setVisible(true);
        desplegableEstadoFinal.setVisible(true);
        etiquetaEstadosFinales.setVisible(false);
        desplegableEstadosFinales.setVisible(false);
    }//GEN-LAST:event_jRadioButtonAFDActionPerformed

    private void jButtonCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompletoActionPerformed

        mxGraphComponent dibujo;
        boolean aceptado = false;
        boolean error = false;
        if (!jTextFieldCadena.getText().isEmpty()) {
            if (jRadioButtonAFD.isSelected()) {

                try {
                    aceptado = automataAFD.reconocer(jTextFieldCadena.getText());

                } catch (Exception ex) {
                    error = true;
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
                }

                if (!error) {
                    if (aceptado) {
                        JOptionPane.showMessageDialog(null, "Cadena aceptada", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Cadena rechazada", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                    }
                }

            }

        } else {
            JOptionPane.showMessageDialog(null, "Cadena vacia", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldCadena.requestFocusInWindow();
        }


    }//GEN-LAST:event_jButtonCompletoActionPerformed

    private void jButtonPasoPasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPasoPasoActionPerformed

        mxGraphComponent dibujo;

        if (!jTextFieldCadena.getText().isEmpty()) {

            if (jRadioButtonAFD.isSelected()) {
                if (iCadena == 0) {
                    estadoActual = automataAFD.getEstadoInicial();
                    dibujo = grafico.pintarPasoAFD(automataAFD, contenerdorEstados, estadoActual);
                }
                estadoActual = automataAFD.getTransicion(estadoActual, jTextFieldCadena.getText().charAt(iCadena));
                contenerdorEstados.addAll(automataAFD.getEstados());
                dibujo = grafico.pintarPasoAFD(automataAFD, contenerdorEstados, estadoActual);

                jScrollPane2.add(dibujo);
                jScrollPane2.getViewport().add(dibujo);
                jScrollPane2.revalidate();
                jScrollPane2.repaint();
                iCadena++;
            }

            if (iCadena == jTextFieldCadena.getText().length()) {
                if (automataAFD.esFinal(estadoActual)) {
                    JOptionPane.showMessageDialog(null, "Cadena aceptada", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Cadena rechazada", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                }
                //jButtonPasoPaso.setEnabled(false);
                iCadena = 0;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cadena vacia", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldCadena.requestFocusInWindow();
        }


    }//GEN-LAST:event_jButtonPasoPasoActionPerformed

    private void jButtonAgregarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarEstadoActionPerformed
        // TODO add your handling code here:

        if (!jTextFieldEstadoAgregar.getText().isEmpty()) {
            automataAFD.setEstado(jTextFieldEstadoAgregar.getText());
            desplegableEstadoInicial.addItem(jTextFieldEstadoAgregar.getText());
            desplegableEstadoFinal.addItem(jTextFieldEstadoAgregar.getText());
            desplegableEstadoOrigen.addItem(jTextFieldEstadoAgregar.getText());
            desplegableEstadoDestino.addItem(jTextFieldEstadoAgregar.getText());
            jTextFieldEstadoAgregar.setText("");
            pintarLienzo();
        }


    }//GEN-LAST:event_jButtonAgregarEstadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        automataAFD.agregarEstadoFinalUnico((String) desplegableEstadoFinal.getSelectedItem());
        automataAFD.setEstadoInicial((String) desplegableEstadoInicial.getSelectedItem());
        pintarLienzo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (!jTextFieldSimboloT.getText().isEmpty()) {
            String origen = (String) desplegableEstadoOrigen.getSelectedItem();
            String destino = (String) desplegableEstadoDestino.getSelectedItem();
            String simboloString = jTextFieldSimboloT.getText();
            char simbolo = simboloString.charAt(0);
            automataAFD.agregarTransicion(origen, simbolo, destino);
            pintarLienzo();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        

        mxGraphComponent dibujo;
        contenerdorEstados.addAll(automataAFD.getEstados());
        dibujo = grafico.pintarAFD(automataAFD, contenerdorEstados);
        if (grafico.isDibujoCompleto()) {
            jButtonPasoPaso.setEnabled(true);
            jButtonCompleto.setEnabled(true);
        }

        jScrollPane2.add(dibujo);
        jScrollPane2.getViewport().add(dibujo);
        jScrollPane2.revalidate();
        jScrollPane2.repaint();

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> desplegableEstadoDestino;
    private javax.swing.JComboBox<String> desplegableEstadoFinal;
    private javax.swing.JComboBox<String> desplegableEstadoInicial;
    private javax.swing.JComboBox<String> desplegableEstadoOrigen;
    private javax.swing.JButton desplegableEstadosFinales;
    private javax.swing.JLabel etiquetaEstadoFinal;
    private javax.swing.JLabel etiquetaEstadoInicial;
    private javax.swing.JLabel etiquetaEstadosFinales;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAgregarEstado;
    private javax.swing.JButton jButtonCompleto;
    private javax.swing.JButton jButtonPasoPaso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButtonAFD;
    private javax.swing.JRadioButton jRadioButtonAFND;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextAreatoStringAutomata;
    private javax.swing.JTextField jTextFieldCadena;
    private javax.swing.JTextField jTextFieldEstadoAgregar;
    private javax.swing.JTextField jTextFieldSimboloT;
    // End of variables declaration//GEN-END:variables
}
